version: '3.8'

services:
  crayon:
    build:
      context: ./services/scraper
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/root/.ssh
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.BaseConfig