
version: 2


sources:
  - name: raw_scrapes
    schema: public
    description: Public Schema with raw data
    tables:
      - name: maxbet_raw
        columns:
          - name: created_at
            description: Created Timestamp
            tests:
              - not_null
      - name: pinnbet_raw
        columns:
          - name: created_at
            description: Created Timestamp
            tests:
              - not_null

models:
  - name: flattened_maxbet
    description: "Flattening odds, matches for Maxbet raw stream"
    columns:
      - name: unique_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: flattened_pinnbet
    description: "Flattening odds, matches for Pinnbet raw stream"
    columns:
      - name: unique_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null